version: '3'
services:
  voting-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:5000"
    environment:
      - REDIS=redis
      - REDIS_PWD=password
  
      

  redis:
    image: "redis:latest"
    command: redis-server --requirepass password

