- name: Déploiement de l'application voting-app
  hosts: localhost
  become: yes

  tasks:
    - name: Assurer que Python 3 est installé (bootstrap Python)
      raw: test -e /usr/bin/python3 || (apt -y update && apt install -y python3-minimal)

    - name: Installer pip pour Python 3
      apt:
        name: python3-pip
        update_cache: yes
        state: present

    - name: Assurer que Git est installé
      apt:
        name: git
        state: present

    - name: Cloner le dépôt depuis GitHub
      git:
        repo: 'https://github.com/Fologix/Voting-app.git'
        dest: /app
        version: main

    - name: Installer les dépendances Python
      pip:
        name:
          - requests
          - redis
          - flask
