name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  lint-and-security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          pip install flake8 bandit

      - name: Lint with flake8
        run: |
          flake8 .

      - name: Security check with bandit
        run: |
          bandit -r .

  build-and-push:
    needs: lint-and-security
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Packer
        run: |
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          sudo apt-add-repository "deb [arch=$(dpkg --print-architecture)] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          sudo apt-get update && sudo apt-get install packer

      - name: Build Docker image with Packer
        run: packer build packer.pkr.hcl

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push image to Docker Hub
        run: |
          Packer should output the name:tag format
          docker push voting-app:tag
          
  deploy-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Lancer le docker-compose en background
      run: docker-compose up -d

    - name: Attendre que l'application soit lancée
      run: sleep 10 # pr que le container soit prêt 

    - name: Installer les dépendances pour les tests
      run: pip install pytest flask

    - name: Exécuter les tests unitaires
      run: pytest

    - name: Nettoyage
      run: docker-compose down
